//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveDirectoryHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClearAfterSuccessfulSearch {
            get {
                return ((bool)(this["ClearAfterSuccessfulSearch"]));
            }
            set {
                this["ClearAfterSuccessfulSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.AutoCompleteStringCollection LastNameList {
            get {
                return ((global::System.Windows.Forms.AutoCompleteStringCollection)(this["LastNameList"]));
            }
            set {
                this["LastNameList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.AutoCompleteStringCollection IdList {
            get {
                return ((global::System.Windows.Forms.AutoCompleteStringCollection)(this["IdList"]));
            }
            set {
                this["IdList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.AutoCompleteStringCollection FirstNameList {
            get {
                return ((global::System.Windows.Forms.AutoCompleteStringCollection)(this["FirstNameList"]));
            }
            set {
                this["FirstNameList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>mydomain.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DomainList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DomainList"]));
            }
            set {
                this["DomainList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>mydomain.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SelectedDomains {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectedDomains"]));
            }
            set {
                this["SelectedDomains"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Michael McKechney")]
        public string ProgramUpdateContact {
            get {
                return ((string)(this["ProgramUpdateContact"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2007-01-01")]
        public global::System.DateTime LastProgramUpdateCheck {
            get {
                return ((global::System.DateTime)(this["LastProgramUpdateCheck"]));
            }
            set {
                this["LastProgramUpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayDisabledAccounts {
            get {
                return ((bool)(this["DisplayDisabledAccounts"]));
            }
            set {
                this["DisplayDisabledAccounts"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://adhelper.sourceforge.net/current_version.txt")]
        public string ProgramVersionCheckURL {
            get {
                return ((string)(this["ProgramVersionCheckURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sourceforge.net/project/showfiles.php?group_id=207498")]
        public string ProgramUpdateURL {
            get {
                return ((string)(this["ProgramUpdateURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Michael@McKechney.com")]
        public string ProgramUpdateContactEmail {
            get {
                return ((string)(this["ProgramUpdateContactEmail"]));
            }
        }
    }
}
